### ISSUE TITLE
Fix for web font IE WSOD bug

### ISSUE THREAD

**Issue by dixhuit** [corysimmons/selectivizr2#2]
[This](https://github.com/JohnCashmore/selectivizr) fork of selectivizr has a [fix](https://github.com/JohnCashmore/selectivizr/commit/e2aa3bebe9b10eaf2d4062c4e757dddb6b159ebf) (untested by myself) for the IE bug where you'd get a WSOD if using web fonts declared in a CSS file.

Were you aware of this? Any plans to work the same fix into this fork?

Thanks for taking this on! :)

**Comment by corysimmons** [comment]
Thanks for the heads up. I'll steal/merge that sometime today.

**Comment by corysimmons** [comment]
Fixed and published. Thanks for the heads up!
