### ISSUE TITLE
not working in IE8

### ISSUE THREAD

**Issue by youngwind** [corysimmons/selectivizr2#5]
hi, I try this in IE8 but it failed.
It's normal in chrome.
<img width="180" alt="2016-03-12 1 36 01" src="https://cloud.githubusercontent.com/assets/8401872/13721135/6aaf06f4-e857-11e5-8323-772c0c51431b.png">
But it does not in IE8
<img width="199" alt="2016-03-12 12 53 51" src="https://cloud.githubusercontent.com/assets/8401872/13721139/7ff92e40-e857-11e5-8daf-eeae8805a58a.png">

My code is below.

```
// html
<link rel="stylesheet" href="/css/index.css"/>
<table>
  <tr>
    <td>1</td>
    <td>2</td>
    <td>1</td>
    <td>2</td>
  </tr>
  <tr>
    <td>3</td>
    <td>4</td>
    <td>3</td>
    <td>4</td>
  </tr>
  <tr>
    <td>5</td>
    <td>6</td>
    <td>5</td>
    <td>6</td>
  </tr>
  <tr>
    <td>7</td>
    <td>8</td>
    <td>7</td>
    <td>8</td>
  </tr>
</table>
<script src="/js/jquery-1.12.0.js"></script>
<script src="/js/selectivizr2.js"></script>
```

```
//css 
tr:nth-child(3){
  background-color: rgba(0,0,0,0.5);
}
```

PS： It does not work neither nth-child nor nth-of-type just like what  I test.

About the source of selectivizr2, I have tried 

```
bower install selectivizr2
```

and download the selectivizr2.js directly from the github.
But they didn't work either.

Please help.

**Comment by corysimmons** [comment]
http://caniuse.com/#feat=css3-colors

![image](https://cloud.githubusercontent.com/assets/224636/13726228/2d25ea16-e88c-11e5-870b-09bd73b7389b.png)

![image](https://cloud.githubusercontent.com/assets/224636/13726230/326253ca-e88c-11e5-9257-c8de7e95323a.png)

![image](https://cloud.githubusercontent.com/assets/224636/13726232/368fa380-e88c-11e5-9285-39ee34d5cb7c.png)

![image](https://cloud.githubusercontent.com/assets/224636/13726233/411103da-e88c-11e5-82ec-47a588429cde.png)

:)

Works with a different color type.

**Comment by youngwind** [comment]
got it, thanks!
