### ISSUE TITLE
not working in cross origin

### ISSUE THREAD

**Issue by youngwind** [corysimmons/selectivizr2#6]
In the [official website](http://selectivizr.com/), author says

> Style sheets MUST be hosted on the same domain as the page due to browser security restrictions. Likewise, style sheets loaded using the file: protocol will not work.

As I know, cross origin is different from origin domain.
For example.

```
http://media.demo.com 
http://www.demo.com 
```

They are cross origin but the same domain.Am I right?

However, when I use selectivizr in cross origin but same domain, it doesn't work! 
Please help.

<img width="805" alt="2016-03-13 11 52 08" src="https://cloud.githubusercontent.com/assets/8401872/13726791/19f759b2-e912-11e5-93d4-b46b03008a74.png">

Below is my host file

```
192.168.1.8     test.smartstudy.com
192.168.1.8     media.smartstudy.com
```

PS: 192.168.1.8 is the ip of my mac, I start the node in my mac and run ie8 in vitualbox.

**Comment by corysimmons** [comment]
I'm sorry I don't have a thorough understanding of how all that cross origin stuff works. You will have better luck on StackOverflow.

If you find an answer, please update this Issue for future users. :+1:

**Comment by dominikwilkowski** [comment]
Mate `test.smartstudy.com` and `media.smartstudy.com` are completely different origins. Same as `smartstudy.com` and `www.smartstudy.com` as subdomains could point to a completely different server. So when the docs say

> same domain

They mean to include subdomains as well. Hope that helps

**Comment by youngwind** [comment]
Got it, thanks! @dominikwilkowski
